# Generated by Django 5.1 on 2024-09-15 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_ca_name_654722_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='category_to_name_99003e_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category_id'], name='category_to_categor_17b8d0_idx'),
        ),
    ]
