# Generated by Django 5.1.3 on 2024-11-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Topic Name'),
        ),
    ]
