# Generated by Django 5.1.3 on 2024-11-29 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('post_type', models.CharField(choices=[('memoir', 'Memoir'), ('journal', 'Journal'), ('poem', 'Poem'), ('story', 'Story'), ('manifesto', 'Manifesto'), ('artwork', 'Artwork'), ('critique', 'Critique'), ('opinion', 'Opinion'), ('review', 'Review'), ('perspective', 'Perspective'), ('reflection', 'Reflection'), ('research', 'Research'), ('experiment', 'Experiment'), ('analysis', 'Analysis'), ('thesis', 'Thesis'), ('case-study', 'Case-Study'), ('proposal', 'Proposal'), ('issue', 'Issue'), ('tutorial', 'Tutorial'), ('guide', 'Guide'), ('announcement', 'Announcement')], default='journal', max_length=20, verbose_name='Post Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnail/', verbose_name='Thumbnail')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_spotlighted', models.BooleanField(default=False, verbose_name='Is Spotlighted')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='category.category', verbose_name='Category')),
                ('topics', models.ManyToManyField(blank=True, related_name='blog_posts', to='category.topic', verbose_name='Topics')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
