# Generated by Django 5.1 on 2024-09-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('journal', 'Journal'), ('opinion', 'Opinion'), ('memoir', 'Memoir'), ('novel', 'Novel'), ('story', 'Story'), ('poem', 'Poem'), ('analysis', 'Analysis'), ('research', 'Research'), ('thesis', 'Thesis'), ('tutorial', 'Tutorial'), ('experiment', 'Experiment'), ('lecture', 'Lecture'), ('manifesto', 'Manifesto'), ('critique', 'Critique'), ('discussion', 'Discussion'), ('review', 'Review')], default='journal', max_length=10),
        ),
    ]
