# Generated by Django 5.1 on 2024-09-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_managers_user_groups_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_member',
            new_name='is_auxiliary',
        ),
    ]
