# Generated by Django 5.1 on 2024-09-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_is_member_user_is_auxiliary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
